server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scx?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: XIAOSUDA
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    mode: LEGACYHTML5
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8

mybatis:
  mapper-locations: "classpath*:mapper/*.xml"

